export const CART_ADD_ITEM = 'CART_ADD_ITEM'
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM'
export const CART_RESET = 'CART_RESET'

export const CREATE_SHIPPING_ADDRESS = 'CREATE_SHIPPING_ADDRESS'
export const RESET_SHIPPING_ADDRESS = 'RESET_SHIPPING_ADDRESS'
